### ISSUE TITLE
Remove hard requirement on `rmarkdown`

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/pacta.portfolio.utils#16]
Move `rmarkdown` to SUGGESTS.

`rmarkdown` is called as part of `prepare_error_report()`:

https://github.com/RMI-PACTA/pacta.portfolio.utils/blob/7752a5c7afa3a84cca93dfd9584a03e608a6d276/R/prepare_error_report.R#L16-L20
https://github.com/RMI-PACTA/pacta.portfolio.utils/blob/7752a5c7afa3a84cca93dfd9584a03e608a6d276/R/prepare_error_report.R#L28-L33

Suggested remedy:

* check if rmarkdown is installed.
  * If so great, do what we're doing now.
  * If not, render a (simpler) file, probably using `writeLines` or something to still dump the user errors in the correct spot, but without formatting
    * Also need to make a simple error PDF letting users who are looking for a PDF output to check that file.

**Comment by cjyetman** [comment]
This is probably the easier solution. There's an issue somewhere about extracting all the TM specific reporting stuff into a separate package, because frankly this entire function is useless except when running on TM.
