### ISSUE TITLE
unify parameter setting into a single function

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/pacta.portfolio.utils#9]
Currently, there are 3 parameter setting functions which must be used in proper order to achieve the desired precedence of options:
- [`set_web_parameters()`](https://github.com/RMI-PACTA/pacta.portfolio.utils/blob/main/R/set_web_parameters.R)
- [`set_portfolio_parameters()`](https://github.com/RMI-PACTA/pacta.portfolio.utils/blob/main/R/set_portfolio_parameters.R)
- [`set_project_parameters()`](https://github.com/RMI-PACTA/pacta.portfolio.utils/blob/main/R/set_project_parameters.R)

It would be advantageous to unify these 3 functions into a single function that properly encodes the order/precedence of options rather than relying on them being used in the proper order as is currently achieved in workflow.transtion.monitor, e.g. here:
https://github.com/RMI-PACTA/workflow.transition.monitor/blob/01033359e4f2e8bbc9ae44db891c3b64f7e9bdb2/web_tool_script_1.R#L24-L28
https://github.com/RMI-PACTA/workflow.transition.monitor/blob/01033359e4f2e8bbc9ae44db891c3b64f7e9bdb2/web_tool_script_2.R#L24-L28
https://github.com/RMI-PACTA/workflow.transition.monitor/blob/01033359e4f2e8bbc9ae44db891c3b64f7e9bdb2/web_tool_script_3.R#L24-L28

Doing so could also more easily facilitate enabling of a single, unified parameter file to be used instead of 3 separate parameter files, a goal of the future web app, without necessarily breaking the existing strategy/workflow.

I'm imagining a function like this:
```r
set_parameters <- 
  function(
    parameters = NULL,
    web_parameters = NULL,
    portfolio_parameters = NULL,
    project_parameters = NULL
  ) {
    # if a single unified parameter file is given, use that
    # ...

    # if 3 specific parameter files are given, merge their options properly
    # ...
  }
```

that way, a single function could be used in either use case, and it would be left up to the workflow designer to decide which type or set of parameter files to use, but the result would be equivalent, e.g. in the existing transition monitor use case, the workflow might use
```r
set_parameters(
  web_parameters = "path/to/web_parameters.yml",
  portfolio_parameters = "path/to/portfolio_parameters.yml",
  project_parameters = "path/to/project_parameters.yml"
)
```
while a workflow for the new web app might use
```r
set_parameters(parameters = "path/to/unified_parameters.yml")
```

This would then facilitate some new function/process for accepting desired options through e.g. a single JSON object/request and converting that to a single `unified_parameters.yml` file which then could easily be ingested as above.

any thoughts @AlexAxthelm @jacobvjk?

**Comment by cjyetman** [comment]
In relation to this, I've started to wonder... why would we ever want to allow/facilitate a user to modify the project/initiative parameters? Those are primarily defined by a COP project agreement, and once defined should likely not be changed. I would imagine keeping those parameters inside the workflow.transition.monitor repo is ideal for version tracking, and we would want to avoid changing/overiding those parameters with a function as suggested above?

**Comment by jdhoffa** [comment]
Sounds logical to me

**Comment by cjyetman** [comment]
> Sounds logical to me

If we go the way of workflow.pacta, these functions are no longer necessary

**Comment by jdhoffa** [comment]
Can you expand on that? I'm still catching up so my brain's not able to make the same jumps I once could lol

**Comment by cjyetman** [comment]
[workflow.pacta](https://github.com/RMI-PACTA/workflow.pacta) does not use these functions at all, it just does this....

https://github.com/RMI-PACTA/workflow.pacta/blob/53fab3f82d4b203911826f7fd4b6fad394a5f64e/pacta_01.R#L11-L20

``` r
cfg_path <- commandArgs(trailingOnly = TRUE)
if (length(cfg_path) == 0 || cfg_path == "") { cfg_path <- "input_dir/default_config.json" }
cfg <- fromJSON(cfg_path)

currencies <- readRDS(file.path(cfg$data_dir, "currencies.rds"))
```

**Comment by AlexAxthelm** [comment]
@cjyetman, The unified function would still be something that set global vars?

If that's the case, my inclination would be to deprecate those functions altogether rather than trying to unify them, and spend that effort on getting workflow.pacta to cover all our needs.

**Comment by cjyetman** [comment]
> @cjyetman, The unified function would still be something that set global vars?
> 
> If that's the case, my inclination would be to deprecate those functions altogether rather than trying to unify them, and spend that effort on getting workflow.pacta to cover all our needs.

Exactly, that's what I did in workflow.pacta (not true deprecation in this repo, but I effectively ignored these functions exist, or any hypothetical unified one). I would prefer that strategy. The PACTA code shouldn't really care **how** you get the needed values/options/parameters.

**Comment by jdhoffa** [comment]
I back it fully!

**Comment by cjyetman** [comment]
Closing in favor of #19
